data:
  path: /home/buzun/promoters2
  train: 
    - fold_1.csv 
    - fold_2.csv
    - fold_3.csv
  test: fold_5.csv
  logsdir: /home/jovyan/pomoika/promoters223
  save_path: /home/jovyan/promoters223.pt
model:
  batch_size: 128
  eval_batch_size: 512
  rec_block_size: 400
  rec_block_padding: 100
  max_token_length: 140
  state_size: 50






